### ISSUE TITLE
README question about exclusions

### ISSUE THREAD

**Issue by AslanGoldenhour** [Mimicry-Protocol/TAMI#8]
I noticed the first transaction in the README says, "Transaction 1 (excluded)" <-- did you mean to include the "(excluded)" … I was confused by that because just above it you wrote, "We'll also ignore the exclusion rules to focus on the calculation itself."

**Comment by dgca** [comment]
Will be fixed in this PR: https://github.com/Mimicry-Protocol/TAMI/pull/10
